apiVersion: v1
kind: Service
metadata:
  labels:
    5gapp: amf
  name: amf
  namespace: default
spec:
  ports:
  - nodePort: 32222
    port: 38412
    protocol: SCTP
    targetPort: 38412
  selector:
    5gapp: amf
  sessionAffinity: None
  type: NodePort
