apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  labels:
    5gapp: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      5gapp: amf
  template:
    metadata:
      labels:
        5gapp: amf
    spec:
      containers:
      - name: amf
        image: oss.registry/free5gc-compose-k8s_free5gc-amf
        volumeMounts:
        - name: config
          mountPath: /free5gc/config/amfcfg.yaml
          subPath: amfcfg.yaml
        env:
        - name: GIN_MODE
          value: release
        command:
        - /free5gc/amf/amf 
        args:
        - -amfcfg 
        - /free5gc/config/amfcfg.yaml
        ports:
        - containerPort: 8000
          protocol: TCP
          name: amf
      volumes:
      - name: config
        configMap:
          name: amfcfg
