apiVersion: v1
data:
  n3iwf-ipsec.sh: "#!/bin/sh\n\n### N3iwf IPSec tunnel configuration\n\n# As per https://github.com/free5gc/free5gc/issues/45#issuecomment-634012712\n#
    \    IKEBindAddress: dynamically computed by $(hostname -i | awk '{print $1}')\n#
    \    IPSecInterfaceMark: 5\n#     IPSecInterfaceAddress: 10.0.0.1\n#     IPSec
    subnet CIDR: /24\n#     N3IWF tunnel interface: ipsec0\n#     \n\nip link add
    name ipsec0 type vti local $(hostname -i | awk '{print $1}') remote 0.0.0.0 key
    5\nip addr add 10.0.0.1/24 dev ipsec0\nip link set dev ipsec0 up\n"
kind: ConfigMap
metadata:
  name: n3iwf-ipsec
  namespace: default
