apiVersion: apps/v1      # added apps/ before the v1 (api group name)
kind: Deployment         # Updated to Deployment
metadata:        ########v
  name: nrf              # same as with Pod
  labels:               #^
    5gapp: nrf   ########
spec:                   # New detailes
  replicas: 1           # How many instances of this pod there should be
  selector:             # How the deployment knows to claim pods (via labels)
    matchLabels:        
      5gapp: nrf
  template:             # The "Pod Template" section. Everything below this is taken
                        # directly from our Pod Manifest - just indented
    metadata:
      labels:
        5gapp: nrf
    spec:
      containers:
      - name: nrf
        image: oss.registry/free5gc-compose-k8s_free5gc-nrf
        volumeMounts:
        - name: config
          mountPath: /free5gc/config/
        env:
        - name: DB_URI
          value: mongodb://db/free5gc
        - name: GIN_MODE
          value: release
        command:
        - /free5gc/nrf/nrf
        args:
        - -nrfcfg
        - /free5gc/config/nrfcfg.yaml
        ports:
        - containerPort: 8000
          protocol: TCP
          name: nrf
      volumes:
      - name: config
        configMap:
          name: nrfcfg
