apiVersion: v1
kind: Service
metadata:
  labels:
    5gapp: nssf
  name: nssf
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    5gapp: nssf
  sessionAffinity: None
  type: ClusterIP
