apiVersion: apps/v1
kind: Deployment
metadata:
  name: nssf
  labels:
    5gapp: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      5gapp: nssf
  template:
    metadata:
      labels:
        5gapp: nssf
    spec:
      containers:
      - name: nssf
        image: oss.registry/free5gc-compose-k8s_free5gc-nssf
        volumeMounts:
        - name: config
          mountPath: /free5gc/config/nssfcfg.yaml
          subPath: nssfcfg.yaml
        env:
        - name: GIN_MODE
          value: release
        command:
        - ./nssf -nssfcfg ../config/nssfcfg.yaml
        ports:
        - containerPort: 8000
          protocol: TCP
          name: nssf
      volumes:
      - name: config
        configMap:
          name: nssfcfg
