apiVersion: v1
kind: Service
metadata:
  labels:
    5gapp: udm
  name: udm
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    5gapp: udm
  sessionAffinity: None
  type: ClusterIP
