apiVersion: v1
kind: ConfigMap
metadata:
  name: upf1cfg
  namespace: default
data:
  upfcfg.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration
    
    configuration:
      # debugLevel: panic|fatal|error|warn|info|debug|trace
      debugLevel: trace 
      
      # The listen IP and nodeID of the N4 interface (this UPF to SMF) (Can't set to 0.0.0.0)
      pfcp:
        # - addr: pfcp.default.svc.cluster.local
        - 127.0.0.1
    
      gtpu:
        # The IP list of interface N3 (This UPF to RAN CU)  OR  interface N9 (This UPF to another UPF)
        # If there are multiple connections, set addr to 0.0.0.0 or list all the addresses
        - addr: 0.0.0.0
        # [optional] gtpu.name
        # - name: upf.5gc.nctu.me
        # [optional] gtpu.ifname
        # - ifname: gtpif
    
      dnn_list:
        - dnn: internet
          cidr: 60.60.0.0/16 # Classless Inter-Domain Routing for assigned IPv4 pool of UE
          # [optional] apn_list[*].natifname
          # natifname: eth0
        - dnn: internet2
          cidr: 10.111.1.0/24 # Classless Inter-Domain Routing for assigned IPv4 pool of UE
          # [optional] apn_list[*].natifname
          # natifname: eth0
