apiVersion: v1
kind: ConfigMap
metadata:
  name: upf1cfg
  namespace: default
data:
  upfcfg.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration
    
    configuration:
      # debugLevel: panic|fatal|error|warn|info|debug|trace
      debugLevel: info

      # The listen IP and nodeID of the N4 interface
      # N4 = (this UPF to SMF)
      # (Can't set to 0.0.0.0)
      pfcp:
        - addr: 127.0.0.1 

      # List of N3/N9 IP Addresses
      # N3 = (This UPF to RAN CU)
      # N9 = (This UPF to another UPF)
      # OK to set addr to 0.0.0.0 = (all addresses)
      gtpu:
        - addr: 127.0.0.1
        # [optional] gtpu.name
        # - name: upf.5gc.nctu.me
        # [optional] gtpu.ifname
        # - ifname: gtpif
    
      dnn_list:
        - dnn: internet
          cidr: 60.60.0.0/16
          # [optional] apn_list[*].natifname
          # natifname: eth0
        - dnn: internet2
          cidr: 10.10.0.0/16
          # [optional] apn_list[*].natifname
          # natifname: eth0
