apiVersion: v1
kind: Service
metadata:
  labels:
    5gapp: upf2
  name: upf2
  namespace: default
spec:
  selector:
    5gapp: upf2
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
  type: ClusterIP
