apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf1
  labels:
    5gapp: upf1
spec:
  replicas: 1
  selector:
    matchLabels:
      5gapp: upf1
  template:
    metadata:
      labels:
        5gapp: upf1
    spec:
      containers:
      - name: upf1
        image: oss.registry/free5gc-compose-k8s_free5gc-upf-1
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: config
          mountPath: /free5gc/config/upfcfg.yaml
          subPath: upfcfg.yaml
        command:
        - /free5gc/free5gc-upfd/free5gc-upfd
        args:
        - -f 
        - /free5gc/config/upfcfg.yaml
      volumes:
      - name: config
        configMap:
          name: upf1cfg
