apiVersion: v1
kind: ConfigMap
metadata:
  name: upf1cfg
  namespace: default
data:
  upfcfg.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration
    
    configuration:
      # debugLevel: panic|fatal|error|warn|info|debug|trace
      debugLevel: trace 
    
      pfcp:
        - addr: pfcp.default.svc.cluster.local 
    
      gtpu:
        - addr: 0.0.0.0
        # [optional] gtpu.name
        # - name: upf.5gc.nctu.me
        # [optional] gtpu.ifname
        # - ifname: gtpif
    
      dnn_list:
        - dnn: internet
          cidr: 60.60.0.0/16
          # [optional] apn_list[*].natifname
          # natifname: eth0
        - dnn: internet2
          cidr: 10.111.1.0/24
          # [optional] apn_list[*].natifname
          # natifname: eth0
