apiVersion: v1
kind: Service
metadata:
  labels:
    5gapp: webui
  name: webui
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    5gapp: webui
  sessionAffinity: None
  type: ClusterIP
